apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/gluetun: "true"
        io.kompose.network/host: "true"
        io.kompose.service: caddy
    spec:
      containers:
        - env:
            - name: CADDY_INGRESS_NETWORKS
              value: host
          image: lucaslorentz/caddy-docker-proxy:alpine
          name: caddy
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: caddy-vol0
              readOnly: true
            - mountPath: /data
              name: caddy-vol1
      restartPolicy: Always
      volumes:
        - name: caddy-vol0
          nfs:
            server: {{ .Values.hostNfsServerAddress }}
            path: {{ .Values.hostBasePersistPath }}/sys/var/run/docker.sock
            readOnly: true
        - name: caddy-vol1
          nfs:
            server: {{ .Values.hostNfsServerAddress }}
            path: {{ .Values.hostBasePersistPath }}/caddy-docker-proxy/data
