apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.hostNetworkName }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/host: "true"
  podSelector:
    matchLabels:
      io.kompose.network/host: "true"
