apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.glueTunNetworkName }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/gluetun: "true"
  podSelector:
    matchLabels:
      io.kompose.network/gluetun: "true"
